# Generated by Django 4.2.5 on 2026-03-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_applog'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
